from decouple import config

MONGO_URI = config("MONGO_URI")
DB_NAME = config("DB_NAME")
PRODUCTS_COLLECTION = config("PRODUCTS_COLLECTION")
USERS_COLLECTION = config("USERS_COLLECTION")

SECRET_KEY = config("SECRET_KEY")
ALGORITHM = config("ALGORITHM")
ACCESS_TOKEN_EXPIRE_MINUTES = config("ACCESS_TOKEN_EXPIRE_MINUTES")